### ISSUE TITLE
AttributeError: 'module' object has no attribute 'convolution' in cifar10_cnn.py

### ISSUE THREAD

**Issue by nndty28** [fchollet/keras#6078]
Trying to run cifar10_cnn.py and I am getting the following error:

`Traceback (most recent call last):
  File "cifar10_cnn.py", line 32, in <module>
    input_shape=x_train.shape[1:]))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 422, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2856, in conv2d
    x = tf.nn.convolution(
AttributeError: 'module' object has no attribute 'convolution'
`

What is going wrong and how do I fix this? I am running it on Ubuntu 16.04, if that helps.

**Comment by mridulbirla** [comment]
Tensorflow needs to be upgraded.

**Comment by atharvap** [comment]
Any fix for this??? Already updated tf this is still persisting .... I reinstalled keras and old codes aren't working

**Comment by mridulbirla** [comment]
I ran the code successfully but was unable to produce the issue.

**Comment by temperatemarine** [comment]
Which version of Keras are you using? For Keras 2, it doesn't work.

**Comment by Pnyxis** [comment]
I have the same problem but I am using Keras 1, is it working for someone using this version?

**Comment by nndty28** [comment]
All of the packages I am using are up to date. I am using Keras 2

**Comment by rabitt** [comment]
@nndty28 I had this problem and was able to fix it by manually upgrading tensorflow.

**Comment by mas-dse-juremigi** [comment]
I am also having this issue with keras 2.0.3 and tensorflow 0.11.0 on mac os 10.12.4.

@rabitt what version did you upgrade to? can you provide step by step?

**Comment by fchollet** [comment]
Keras 2 is meant for TF 1.0 or higher.

**Comment by rabitt** [comment]
@mas-dse-juremigi I'm running tensorflow 1.0.1

**Comment by tmiyatak** [comment]
FYI I had the same problem, so I updated to keras 2.0.2 and tensorflow 1.0.1 and it's working now on my Mac OS with Anaconda Python 2.7.

**Comment by RaviKumarVenkat** [comment]
I am facing the same issue. I am using Keras (2.0.2) and tensorflow (1.0.1). 
![conv2d_error](https://cloud.githubusercontent.com/assets/1225170/25565514/c6521ba2-2de5-11e7-85db-b92335b41d7e.png)

**Comment by nicoTrombon** [comment]
I had the same problem, updated to keras 2.0.4 and it's working now. Working with Ubuntu and Python 2.7.

**Comment by sicongkuang** [comment]
I had the same problem. But everything is updated. Still get the 'module' object has no attribute 'convolution'.  tensorflow 1.1.0,  keras 2.0.2, python 2.7.  Any advice?
