### ISSUE TITLE
mnist_siamese_graph.py gives an error

### ISSUE THREAD

**Issue by xpact** [fchollet/keras#2125]
Updated theano and keras to latest version from github. Running python mnist_siamese_graph.py gives following error:
Traceback (most recent call last):
  File "mnist_siamese_graph.py", line 111, in <module>
    g.compile(loss={'output': contrastive_loss}, optimizer=rms)
  File "~/anaconda/lib/python2.7/site-packages/keras/models.py", line 1265, in compile
    if self.outputs[self.output_order[0]].output_shape[-1] == 1:
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by PhyloStar** [comment]
Got the same error with Keras 0.3.3. Works with Keras 0.3.2
