### ISSUE TITLE
keras.utils.dot_utils.Grapher() doesn't work with Graph() models

### ISSUE THREAD

**Issue by grahamannett** [fchollet/keras#688]
I think I completely understand why this doesn't work (and I am attempting to make a better visualizer for keras than current one which uses pydot), but was wondering if this is something anyone thinks is relevant:

```
from keras.layers.core import Dense, Activation
from keras.utils.dot_utils import Grapher
from keras.models import Graph
graph = Graph()
graph.add_input(name='input', ndim=2)
graph.add_node(Dense(32, 16), name='dense1', input='input')
graph.add_node(Dense(32, 4), name='dense2', input='input')
graph.add_node(Dense(16, 4), name='dense3', input='dense1')
graph.add_output(name='output1', input='dense2')
graph.add_output(name='output2', input='dense3')
grapher = Grapher()
grapher.plot(graph, 'graph.png')


AttributeError                            Traceback (most recent call last)
<ipython-input-11-83ed46142968> in <module>()
----> 1 grapher.plot(graph, 'graph.png')

/Users/graham/.virtualenvs/niche/lib/python3.4/site-packages/keras/utils/dot_utils.py in plot(self, model, to_file)
     50         """
     51         graph = pydot.Dot(graph_type='graph')
---> 52         self.add_model(model, graph)
     53         graph.write_png(to_file)

/Users/graham/.virtualenvs/niche/lib/python3.4/site-packages/keras/utils/dot_utils.py in add_model(self, model, graph, parent)
     36         if isinstance(model, Model):
     37             parent = self.add_edge(parent, this, graph)
---> 38             for child in reversed(model.layers):
     39                 parent = self.add_model(child, graph, parent)
     40         elif isinstance(model, Merge):

AttributeError: 'Graph' object has no attribute 'layers'

```

i don't think it's crazy to add a visualization ability to the Graph() models as in this: https://github.com/google/inception/blob/master/inception.ipynb 
on output[3] there is a visualization of a DNN that I believe is what a Graph() model could potentially look like?

**Comment by grahamannett** [comment]
Also, I'm not sure why but the Grapher class doesnt seem to be in keras anymore(even though with install from pip it's listed as this current version but has Grapher class), I think it would be very easy to add a simple thing like:

```
import pydot


def plot(model, to_file):

    graph = pydot.Dot(graph_type='digraph')

    previous_node = None
    written_nodes = []
    n = 1
    for node in model.get_config()['layers']:
        if (node['name'] + str(n)) in written_nodes:
            n += 1
        current_node = pydot.Node(node['name'] + str(n))
        written_nodes.append(node['name'] + str(n))
        graph.add_node(current_node)
        if previous_node:
            graph.add_edge(pydot.Edge(previous_node, current_node))
        previous_node = current_node
    graph.write_png(to_file)
```

for sequential models since that draws arrows and is top down (where as previously the output was on the top of the image)

I think the naming scheme I'm using is bad but couldn't find an easier way to identify layers labeled same thing.

**Comment by grahamannett** [comment]
something like this will work for both [graph examples](http://keras.io/models/#graph) and any of the examples (such as MLP example)

```
import pydot


def plot(model, to_file='model.png'):

    graph = pydot.Dot(graph_type='digraph')
    if type(model) == Sequential:
        previous_node = None
        written_nodes = []
        n = 1
        for node in model.get_config()['layers']:
            # append number in case layers have same name to differentiate
            if (node['name'] + str(n)) in written_nodes:
                n += 1
            current_node = pydot.Node(node['name'] + str(n))
            written_nodes.append(node['name'] + str(n))
            graph.add_node(current_node)
            if previous_node:
                graph.add_edge(pydot.Edge(previous_node, current_node))
            previous_node = current_node
        graph.write_png(to_file)

    elif type(model) == Graph:
        # don't need to append number for names since all nodes labeled
        for input_node in model.input_config:
            graph.add_node(pydot.Node(input_node['name']))

        # intermediate and output nodes have input defined
        for layer_config in [model.node_config, model.output_config]:
            for node in layer_config:
                graph.add_node(pydot.Node(node['name']))
                # possible to have multiple 'inputs' vs 1 'input'
                if node['inputs']:
                    for e in node['inputs']:
                        graph.add_edge(pydot.Edge(e, node['name']))
                else:
                    graph.add_edge(pydot.Edge(node['input'], node['name']))

        graph.write_png(to_file)
```


MLP example
![model](https://cloud.githubusercontent.com/assets/7343667/9895155/1e39cd7a-5be1-11e5-899f-73a6a7eff1ad.png)

Graph 1 example
![graph1](https://cloud.githubusercontent.com/assets/7343667/9895114/9d3b168e-5be0-11e5-8cad-9276f3589e68.png)

Graph 2 example
![graph2](https://cloud.githubusercontent.com/assets/7343667/9895115/9d3e7c02-5be0-11e5-8083-7a1c67abf4ef.png)

**Comment by fchollet** [comment]
I removed the grapher util earlier because I realized nobody used it. It had been broken long ago in some API update, which we didn't know because we didn't have any tests for it. It stayed broken for a few months and nobody complained --presumably because nobody ever used it during that time.

I you want to reintroduce it, why not. You can make a PR if you want, I will review it.

**Comment by arisliang** [comment]
Reintroduce it would be nice.

**Comment by carlthome** [comment]
:+1:

**Comment by carlthome** [comment]
Awww...

**Comment by carlthome** [comment]
@fchollet, Theano supplies utils for [drawing the computational graph](http://deeplearning.net/software/theano/tutorial/printing_drawing.html) already. Is it possible to return the compiled Theano function from `keras.model.compile()` somehow so we can use that instead?

**Comment by tboquet** [comment]
The util has been reintroduced and you could use it like this:

```python
from keras.utils.visualize_util import plot, to_graph
graph = to_graph(model, show_shape=True)
graph.write_png("model.png")
```

You could draw the computation graph like this:

```python
import theano.d3viz as d3v
d3v.d3viz(model.get_output(), 'test.html')
```

**Comment by carlthome** [comment]
@tboquet, wonderful! Thanks for the instructions. :+1:

**Comment by yrevar** [comment]
@tboquet, thanks :+1:

**Comment by tammyyang** [comment]
Hi, I found the tool no longer exists in Keras 1.0, and keras.utils.visualize_util.plot fails to work with Graph model with the following error: 

```
AttributeError: 'Graph' object has no attribute 'layers'
```

I tried to modify @grahamannett's plot function a little bit to make it work with Keras 1.0

```
def plot(model, to_file='model.png'):                                           
                                                                                
    graph = pydot.Dot(graph_type='digraph')                                     
    if type(model) == Sequential:                                                                                                              
        previous_node = None                                                                                                                   
        written_nodes = []                                                      
        n = 1                                                                                                                                  
        for layer in model.layers:                                              
            # append number in case layers have same name to differentiate      
            config = layer.get_config()                                         
            if (config['name'] + str(n)) in written_nodes:                      
                n += 1                                                          
            current_node = pydot.Node(config['name'] + str(n))                  
            written_nodes.append(config['name'] + str(n))                       
            graph.add_node(current_node)                                            
            if previous_node:                                                   
                graph.add_edge(pydot.Edge(previous_node, current_node))             
            previous_node = current_node                                                
        graph.write_png(to_file)                                                    
                                                                                    
    elif type(model) == Graph:                                                      
        config = model.get_config()                                                 
        # don't need to append number for names since all nodes labeled                 
        for input_node in config['input_config']:                                   
            graph.add_node(pydot.Node(input_node['name']))                      
                                                                                
        # intermediate and output nodes have input defined                      
        for layer_config in [config['node_config'], config['output_config']]:   
            for node in layer_config:                                           
                graph.add_node(pydot.Node(node['name']))                        
                # possible to have multiple 'inputs' vs 1 'input'               
                if node['inputs']:                                              
                    for e in node['inputs']:                                    
                        graph.add_edge(pydot.Edge(e, node['name']))             
                else:                                                           
                    graph.add_edge(pydot.Edge(node['input'], node['name']))     
                                                                                
        graph.write_png(to_file)    
```
It works on mnist_cnn.py example (Sequential) and the [SqueezeNet](https://github.com/jianminsun/Keras_SqueezeNet) (Graph) model
