### ISSUE TITLE
fit_generator broken in 0.3.2?

### ISSUE THREAD

**Issue by ttal** [fchollet/keras#1857]
After upgrading to 0.3.2 I noticed that model fitting with fit_generator is slower than it used to be.  I tested this with a simple LSTM net (theano backed) on a single gpu core AWS instance, and found that 0.3.2 is about 20 times slower than 0.3.1.  Any ideas to why that is?  The differemce in speed is sort of similar to using cpu vs. gpu I think.

Also, somewhat related, the new nb_val_samples that recently appeared in the docs is not actually implemented in 0.3.2 (but is in the git version).

**Comment by fchollet** [comment]
If you can track that to a specific commit, I will look at it.

**Comment by ttal** [comment]
Not sure - whichever one associated with the pypi release version 0.3.2 that was committed a couple of weeks ago.

**Comment by fchollet** [comment]
This one I guess: https://github.com/fchollet/keras/commit/d1a3842b3d476aaf8479ec4dc3a9eff6ad35e8b6#diff-98d8790a4331685d2a81334c398c4b58

@qdbp thoughts?

**Comment by KeironO** [comment]
Not sure if related, but ```validation_split``` no longer works on 0.3.2 either.

```python
Traceback (most recent call last):
  File "/home/keo7/.projects/neural-network-plant-trait-classification/neural_networks/flower_colour.py", line 152, in <module>
    model = train_model(model, data[train], labels[train], number_of_classes)
  File "/home/keo7/.projects/neural-network-plant-trait-classification/neural_networks/flower_colour.py", line 82, in train_model
    nb_worker=1)
TypeError: fit_generator() got an unexpected keyword argument 'validation_split'
```

**Comment by qdbp** [comment]
This is likely related to some changes I had made, I am looking into it.

**Comment by ttal** [comment]
@qdbp just for training - I load a subset into memory for validation so that I can compare side-by-side with memory-based training without validation being an issue.

**Comment by KeironO** [comment]
Can anyone confirm if the new release works?

**Comment by ttal** [comment]
not sure what your most recent commit does but it's not working for me.  The main issue (huge slowdown when I use fit_generator) is still there.  The secondary issue (nb_val_samples not implemented) is still there as far as I can tell.

**Comment by qdbp** [comment]
@KeironO I don't recall `fit_generator` ever having a `validation_split` parameter, since iirc that is for breaking off a validation set from a fixed datset.
@ttal That's unfortunate. I checked that `create_gen_queue` function operates correctly (at least now that it actually gets the right `nb_worker`). That it's training that's slow eliminates `evaluate_generator` as the culprit. `verify_generator_output` also seems safe, and is old code. Perhaps I should do some profiling.

**Comment by gpleiss** [comment]
The `nb_val_samples` argument was recently added in a commit (10-ish days ago). There has been no release sense this was added.

@fchollet when is the next release planned?

**Comment by ttal** [comment]
@gpleiss it is in the [docs](http://keras.io/models/#model-api-documentation) nonetheless.

Any thoughts about why fi_generator is so much slower in the latest release than in previous ones?

**Comment by qdbp** [comment]
I'm debugging this now: It _is_ `generator_queue` that's misbehaving. Despite getting the right nb_worker it seems to not yield in parallel.
